# Generated by Django 5.2.1 on 2025-09-12 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('team_avg_goals_per_match', models.FloatField(blank=True, null=True)),
                ('team_avg_goals_conceded', models.FloatField(blank=True, null=True)),
                ('team_clean_sheet_rate', models.FloatField(blank=True, null=True)),
                ('matches_played', models.IntegerField(blank=True, null=True)),
                ('goals_scored_total', models.IntegerField(blank=True, null=True)),
                ('goals_conceded_total', models.IntegerField(blank=True, null=True)),
                ('clean_sheets', models.IntegerField(blank=True, null=True)),
                ('team_avg_shots', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('position_encoded', models.IntegerField(blank=True, null=True)),
                ('minutes', models.FloatField(blank=True, null=True)),
                ('appearances', models.FloatField(blank=True, null=True)),
                ('goals', models.FloatField(blank=True, null=True)),
                ('assists', models.FloatField(blank=True, null=True)),
                ('shots_total', models.FloatField(blank=True, null=True)),
                ('shots_on', models.FloatField(blank=True, null=True)),
                ('passes_total', models.FloatField(blank=True, null=True)),
                ('passes_key', models.FloatField(blank=True, null=True)),
                ('avg_minutes_played', models.FloatField(blank=True, null=True)),
                ('shots_per_game', models.FloatField(blank=True, null=True)),
                ('conversion_rate', models.FloatField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='ai_app.team')),
            ],
        ),
    ]
